# Setup
title:            Chris Glein
tagline:          'Game Design and Life'
description:      'Game design, and musings on life in general'
baseurl:          /
url:              https://chrisglein.com
paginate:         5

# About/contact
author:
  name:           'Chris Glein'
  url:            https://chrisglein.com

# Gems
plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Chris Glein"