# Setup
title:            Chris Glein
tagline:          'Game Design and Life'
description:      'Game design, and musings on life in general'
baseurl:          /
url:              https://chrisglein.com
paginate:         3

excerpt_separator:  <!--more-->

related_by: tags                # Match on just tags
related_limit: 5                # Include 5 related pages
related_categories: 1           # Must match at least X categorys
related_tags: 2                 # Must match at least X tags

# About/contact
author:
  name:           'Chris Glein'
  url:            https://chrisglein.com

# Gems
plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Chris Glein"