remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"
      author: "Chris Glein"