# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Chris Glein
tagline:          'Game Design'
description:      'Game design projects and musings from Chris Glein'

author:
  name:           'Chris Glein'
  url:            https://twitter.com/mdo

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"
      author: "Chris Glein"