# Setup
title:            Chris Glein
tagline:          'Game Design'
description:      'Game design projects and musings'
baseurl:          /
url:              https://chrisglein.com
paginate:         5
permalink:        pretty

# About/contact
author:
  name:           'Chris Glein'
  url:            https://chrisglein.com

# Gems
plugins:
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"
      author: "Chris Glein"