# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Setup
title:            Chris Glein
tagline:          'Game Design'
description:      'Game design projects and musings'
url:              http://chrisglein.com
baseurl:          /

author:
  name:           'Chris Glein'
  url:            https://chrisglein.com

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "post"
      author: "Chris Glein"