---
layout: post
title: MustEatBrains - Update 1
date: '2011-08-05T08:00:00.000-07:00'
author: Chris Glein
tags:
- zombie
- videogame
- musteatbrains
modified_time: '2011-08-05T08:13:30.096-07:00'
thumbnail: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgSfU_PWOQEFgr_Cs8nCEcwVB8FKh_pO5XU5gcqGyyAQIfHX_k_9lyA-KxoRcmvUAhy-qMVYljIcAOmGxluSsdFMkoqFkAt2E92TQ6EPSzFzXPabtAdeVSTcAuhdwV4rgcjRXd-nGZvt_4/s72-c/newscores.png
blogger_id: tag:blogger.com,1999:blog-2342422231079442130.post-7921838348658307594
blogger_orig_url: https://chrisglein.blogspot.com/2011/08/in-olden-days-software-was-bought-in.html
---

<div style="font-family: Calibri; font-size: 11pt; margin: 0in;">In the olden days, software was bought in a real physical store, came in a physical box, and was written onto some piece of physical media.<span style="mso-spacerun: yes;">&nbsp; </span>If that software had problems with it, or lacked important features, then there was no real way to get an update out to the consumer.<span style="mso-spacerun: yes;">&nbsp; </span>I think once or twice I had a game with such bad defects that they mailed out replacement floppy disks, but it was exceedingly rare.<span style="mso-spacerun: yes;">&nbsp; </span>In general the mantra was "get it the right the first time, or don't bother."</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br />
Today's culture is incredibly different.<span style="mso-spacerun: yes;">&nbsp; </span>Digital distribution has become<span style="mso-spacerun: yes;">&nbsp; </span>the norm.<span style="mso-spacerun: yes;">&nbsp; </span>Even if you bought a box in a store, you're invariably going to get updates pushed to you from the internet.<span style="mso-spacerun: yes;">&nbsp; </span>Software has become a living, breathing thing.<span style="mso-spacerun: yes;">&nbsp; </span>And it's changed both how people develop software and how they consume it.<span style="mso-spacerun: yes;">&nbsp; </span>The mantra has shifted to "release early and often."</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br />
Given that my game lives on a internet connected device, I opted for a modern development strategy.<span style="mso-spacerun: yes;">&nbsp; </span>I don't bring any of this up to say that I rushed something unfinished out the door.<span style="mso-spacerun: yes;">&nbsp; </span>Not at all - I think my little game is awesome.<span style="mso-spacerun: yes;">&nbsp; </span>But I don't see it as a product that is done - I see it as the beginning of things to come.</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br />
For the first release I knew that certain things needed to be established.<span style="mso-spacerun: yes;">&nbsp; </span>I needed to solidify a visual style, and I needed to have the core gameplay be tight.<span style="mso-spacerun: yes;">&nbsp; </span>As long as it was fun, and looked like something I wanted to play, some details could wait.<span style="mso-spacerun: yes;">&nbsp; </span>If I tried to do every thing I wanted in one release then I'd never ever finish.</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br />
The point:<span style="mso-spacerun: yes;">&nbsp; </span>I am happy to announce that the first update for <a href="http://windowsphone.com/s?appid=feabce8d-c6af-e011-a53c-78e7d1fa76f8">MustEatBrains</a> is now available!<br />
<div></div></div><br />
<div class="separator" style="clear: both; text-align: center;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgSfU_PWOQEFgr_Cs8nCEcwVB8FKh_pO5XU5gcqGyyAQIfHX_k_9lyA-KxoRcmvUAhy-qMVYljIcAOmGxluSsdFMkoqFkAt2E92TQ6EPSzFzXPabtAdeVSTcAuhdwV4rgcjRXd-nGZvt_4/s1600/newscores.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="192" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgSfU_PWOQEFgr_Cs8nCEcwVB8FKh_pO5XU5gcqGyyAQIfHX_k_9lyA-KxoRcmvUAhy-qMVYljIcAOmGxluSsdFMkoqFkAt2E92TQ6EPSzFzXPabtAdeVSTcAuhdwV4rgcjRXd-nGZvt_4/s320/newscores.png" width="320" /></a></div><div class="separator" style="clear: both; text-align: center;"><br />
</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;">The game as it exists today is essentially a little action game where you try for a new top score.<span style="mso-spacerun: yes;">&nbsp; </span>But without being able to compete with other people there's not much meaning to that.<span style="mso-spacerun: yes;">&nbsp; </span>So it was clear that the first thing I needed to add was online leaderboards.<span style="mso-spacerun: yes;">&nbsp; </span>With the new update you'll be able to submit your scores and see how you compare to the top scores for the day or the top scores of all time.<br />
<div></div></div><br />
<div class="separator" style="clear: both; text-align: center;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxDYGxK4D6-vu3wJTv7eWzwJ4zbfVWvs9JBVae88d6ShIjuxXDH5zZevX2SjHmlmef1_KzrZU6Ctuic7XL9UOuwkneJAr59ZUO8sjDaPHSkg3sQ4MXOJ06GKMXRMgmIvmRYgQDM7ubpbg/s1600/stats.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="192" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxDYGxK4D6-vu3wJTv7eWzwJ4zbfVWvs9JBVae88d6ShIjuxXDH5zZevX2SjHmlmef1_KzrZU6Ctuic7XL9UOuwkneJAr59ZUO8sjDaPHSkg3sQ4MXOJ06GKMXRMgmIvmRYgQDM7ubpbg/s320/stats.png" width="320" /></a></div><div></div><br />
<div style="font-family: Calibri; font-size: 11pt; margin: 0in;">Of course with this focus on score I wanted to give the player more info on how they got to the score they did.<span style="mso-spacerun: yes;">&nbsp; </span>So I implemented a little post-game summary page that breaks down what carnage you inflicted and how you inflicted it.<span style="mso-spacerun: yes;">&nbsp; </span>Nothing too fancy, just a little info to satisfy the data nerd in all of us.<br />
<div></div></div><br />
<div class="separator" style="clear: both; text-align: center;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhbbx8R_RDXaULk49yQoWglSrLeKfSaZeLq-g6DyXFXnwgzRF_u9Ie_ZR53hjz-8iGQOEBma9mIYApPwJ-q_JXTF4zhv2nrmEpCMw3sTPDEvr0I0YVWOoBpZFTb6oapbZHtCLsGHATCsOk/s1600/leaphelp.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="192" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhbbx8R_RDXaULk49yQoWglSrLeKfSaZeLq-g6DyXFXnwgzRF_u9Ie_ZR53hjz-8iGQOEBma9mIYApPwJ-q_JXTF4zhv2nrmEpCMw3sTPDEvr0I0YVWOoBpZFTb6oapbZHtCLsGHATCsOk/s320/leaphelp.png" width="320" /></a></div><div></div><br />
<div style="font-family: Calibri; font-size: 11pt; margin: 0in;">I was really happy with the Living game mode at launch.<span style="mso-spacerun: yes;">&nbsp; </span>And I thought it was cool that you could turn things around and play as the undead.<span style="mso-spacerun: yes;">&nbsp; </span>But the Undead mode suffered from a lack of variety.<span style="mso-spacerun: yes;">&nbsp; </span>The living player has multiple weapons at her disposal, and has to keep moving around tactically in order to stay alive.<span style="mso-spacerun: yes;">&nbsp; </span>The undead player merely had to keep up an aggressive chase to maintain a steady supply of brains.<span style="mso-spacerun: yes;">&nbsp; </span>Compared to the dynamic gameplay of the living player it just wasn't fun enough.</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br />
After sitting on the problem for a while I decided the zombie player needed a better way to close the gap.<span style="mso-spacerun: yes;">&nbsp; </span>Less time chasing, more time doing what zombies do best.<span style="mso-spacerun: yes;">&nbsp; </span>So I gave the zombie a leap attack.</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br />
I wanted to keep the ravenous lust for brains a key part of the game, so I put the leap attack on a stamina system.<span style="mso-spacerun: yes;">&nbsp; </span>Leaping takes a lot of stamina, which will slowly regenerate over time; however tasty human parts will refill that meter <span style="font-style: italic;">much</span> faster.<span style="mso-spacerun: yes;">&nbsp; </span>So as a zombie player you're always on the look out for edibles.<span style="mso-spacerun: yes;">&nbsp; </span>It adds the slightest bit of resource management, but not too much.</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br />
As it stands the undead mode is pretty hard.<span style="mso-spacerun: yes;">&nbsp; </span>I'll likely tweak that with future updates, but on the whole I'm happy with how it feels.<span style="mso-spacerun: yes;">&nbsp; </span>As a zombie you're an underdog, both working with and competing against your undead compatriots for whatever human parts are available.<span style="mso-spacerun: yes;">&nbsp; </span>It's hard, but it's <i>thematically</i> hard.<br />
<div></div></div><br />
<div class="separator" style="clear: both; text-align: center;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjcQJLV1-QuURZYlHl7PigMd0FrIu3R3ZI-htY-bb6a3GjzagcPJP1-sMTm857hd5chFT_WMlTQjENcyZ2MMfMzvTrbg31_RNdSBwGfHitw_9FBoydzfFLnEK8F1cLOPEWwK7o64GYiPls/s1600/leapgameplay.png" imageanchor="1" style="margin-left: 1em; margin-right: 1em;"><img border="0" height="192" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjcQJLV1-QuURZYlHl7PigMd0FrIu3R3ZI-htY-bb6a3GjzagcPJP1-sMTm857hd5chFT_WMlTQjENcyZ2MMfMzvTrbg31_RNdSBwGfHitw_9FBoydzfFLnEK8F1cLOPEWwK7o64GYiPls/s320/leapgameplay.png" width="320" /></a></div><div></div><br />
<div style="font-family: Calibri; font-size: 11pt; margin: 0in;">So, that's what's in the update.<span style="mso-spacerun: yes;">&nbsp; </span>It also includes various balance tweaks (especially around the late game) and interface refinements.<span style="mso-spacerun: yes;">&nbsp; </span>But the core features are what's listed above.</div><div style="font-family: Calibri; font-size: 11pt; margin: 0in;"><br />
What's next?<span style="mso-spacerun: yes;">&nbsp; </span>Well, the feedback is pretty clear.<span style="mso-spacerun: yes;">&nbsp; </span>The next features people want to see are:</div><ul><li><div style="margin-bottom: 0px; margin-top: 0px; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11pt;">Sound</span></div></li>
<li><div style="margin-bottom: 0px; margin-top: 0px; vertical-align: middle;"><span style="font-family: Calibri; font-size: 11pt;">More varied environments</span></div></li>
</ul><div style="font-family: Calibri; font-size: 11pt; margin: 0in;">So those are definitely in the pipeline.<span style="mso-spacerun: yes;">&nbsp; </span>As well as some more fun stuff that I'll share with you soon enough.<span style="mso-spacerun: yes;">&nbsp; </span>Until then, sit back, relax, and <a href="http://windowsphone.com/s?appid=feabce8d-c6af-e011-a53c-78e7d1fa76f8">eat some brains</a>!</div>