---
layout: post
title: Music Made Me - Part 10
date: '2012-03-06T21:44:00.000-08:00'
author: Chris Glein
tags:
- music
- musicmademe
modified_time: '2012-03-06T21:44:00.686-08:00'
blogger_id: tag:blogger.com,1999:blog-2342422231079442130.post-2947404228877837617
blogger_orig_url: https://chrisglein.blogspot.com/2012/03/music-made-me-part-10.html
---

<p><a href="zune://navigate/?trackID=3AE30D00-0500-11DB-89CA-0019B92A3933">Under the Bridge - The Red Hot Chili Peppers</a></p>  <p>I put this song far later into the timeline than when I first experienced it (which would have been 1991-1992). That's because to me it goes with a very specific memory, one which eclipsed whatever previous attachment I had for the song.</p>  <p>I'm on the return trip from my one and only experience ice skating. I'm riding in the back seat with a girl. I've been seeing more of this girl at school lately, and I've decided I like her. Somehow I muster the courage to sing this song to her. I'm sure it must have been along to the radio, not unprompted a capella, although over the years my voice has grown louder and the radio has grown quieter. Following this there was some head-resting-on-shoulder action. Apparently it wasn't so terrible as to make her run away.&#160; She must have liked me, because it's not like I can sing.</p>  
<!--more-->

<p><a href="zune://navigate/?trackID=AB400800-0100-11DB-89CA-0019B92A3933">Three Marlenas - The Wallflowers</a></p>  <p>I remember a discussion about what was the best song on this album between myself, my brother, and my brother's girlfriend Francesca. The decision made (at least by that vote) was that it was &quot;Three Marlenas&quot;. It's a good song, sure, but I think perhaps my brother may have been unduly influenced by the fact that the song mentions Chevrolet; he was a bit of a fanatic back then.</p>  <p>I'm sure my brother only has vile things to say about her now, but I really liked my brother's girlfriend. It was like having a big sister. She could give me advice that I very much needed.</p>  <p>At this moment in time I had a viable prospective love interest. A first.&#160; As in a girl that seemed to like me back, and I thought we might kiss. Which I have never done before. Oh crap!</p>  <p>Francesca gave me the invaluable tip to practice kissing on my hand first. This is the sort of thing you need a sister to tell you to do. I felt more than a bit silly, but it better to work out the kinks well in advance. I don't know how awful I was, but I'm sure I would have been way worse without that advice.</p>  

<p><a href="zune://navigate/?trackID=D0A0E806-0100-11DB-89CA-0019B92A3933">Comedown - Bush</a></p>  <p>For me this is the point where we transitioned from calling it &quot;grunge&quot; to calling it &quot;alternative&quot;. I mean, this is a pretty man. How can the music made by pretty people be called &quot;grunge&quot;?</p>  <p>This was an influence from my newfound girlfriend (!) Cambria. It wasn't a lasting impression musically, but it was nice that we could listen to the same things. I recall her not having a problem with the lead singer being a pretty man.</p>  <p>I had an image in my brain from the music video for this song. In my head I see a guitar cord that's a big tube and someone aggressively thrusting a guitar towards the camera. The particular image coincides with 3:33 in the song, where the music lands after drifting away a bit and is celebrated with a masterfully singular guitar hit. It's the powerful return to form that &quot;Lightning Crashes&quot; didn't have. Anyway, I had an image in my head of what that looks like in the music video. And I just watched it <a href="http://www.youtube.com/watch?v=epPW_-da6oQ&amp;ob=av2e">again</a> and it's not there. Clearly I remembered the video, but in my head the details are incredibly different. The edit of the song for the video is shorter, so the same moment happens at 2:47. I don't know when my memory drifted apart from reality. The specific image I have doesn't occur anywhere in that video. It's weird to have a concrete image in your head that is provably <em>wrong</em>. </p>  

<p><a href="zune://navigate/?trackID=4AD81800-0500-11DB-89CA-0019B92A3933">Lucky - Seven Mary Three</a></p>  <p>This album is the greatest musical takeaway from my relationship with Cambria. After my general dissatisfaction with the previous Seven Mary Three album I hadn't followed up on the band. I should have, because the next album, this album, is great.</p>  <p>Well, great-<em>ish</em>. The correct way to experience this album is to listen to the first track (&quot;Lucky&quot;), and then skip ahead to track 4 (&quot;Honey Generation&quot;), and after that move to 6 (&quot;People Like New&quot;) to ride out the rest of the album. I believed this so strongly that years later when I ripped the CD (digital music, crazy I know) I deleted those tracks (2, 3, and 5) entirely. Right now, as I'm writing this, I'm listening to them for the first time in at least a decade.</p>  <p>It's not that those songs are the worst <em>ever</em>. They're just wrong for the album. I feel like I'm repeating myself here, but the B-side of this album <em>is</em> the album. It has a sound, and that sound is <em>good</em>. That stuff at the beginning just gets in the way.</p>  <p>So why &quot;Lucky&quot;? Well, there would have been an easy way to bypass my problem entirely: always start at track 6. But I could never listen to the album without &quot;Lucky&quot;. That would just be <em>wrong</em>. I would rather tolerate the pain of having to wait for the song to end and then quickly skip ahead past the bad stuff. The song was (and is) that good.</p>  

<p><a href="zune://navigate/?trackID=31520A00-0100-11DB-89CA-0019B92A3933">Soldier's Daughter - Tonic</a></p>  <p>Here we have another album brought to my attention by my first girlfriend. Shortly after hearing this song I decided I was going to attempt to learn how to play it for her. But playing it wasn't enough, I was going to both provide guitar <em>and</em> vocals. This is not something I actually could (or can) do, mind you. I don't know if it's the guitar playing or the singing that takes more concentration, but what matters is that the combination requires more than I have. So this was a doomed desire from the outset and thus never fully materialized.</p>  <p>One key thing made it even possible to attempt in the first place. That thing is the internet. Yes, we have an internet now at this point in the timeline. I know this because I looked up the guitar tablature for this song on the internet. Back in '97 with some pre-Google search engine.</p>  <p>The end result of all of this is that I know the song rather well. Not well enough, of course, but well. And I still like it, because it's a great song. I like the album as a whole, actually. It's something I only really listened to during this time in my life, but I feel like deserves more.</p>  