// Neva's favorite-movies bracket — 64 films (a power of 2, no byes needed).
// Sourced from "Neva Top All Time Movies" (year-review favorites + likely picks).
//
// Fields:
//   id    — slug used as a stable key for art lookup
//   title — display title shown on cards
//   imdb  — IMDb page URL (shown as a link pill on each card)
//
// The engine reads window.ITEMS. Swap this file to rank a different set
// (e.g. a "Chris's favorite movies" list) without touching the engine.
window.ITEMS = [
  { id: "dnd-honor-among-thieves",          title: "D&D: Honor Among Thieves",             imdb: "https://www.imdb.com/title/tt2906216/" },
  { id: "wild-robot",                       title: "The Wild Robot",                       imdb: "https://www.imdb.com/title/tt29623480/" },
  { id: "kpop-demon-hunters",               title: "K-Pop Demon Hunters",                  imdb: "https://www.imdb.com/title/tt14205554/" },
  { id: "my-neighbor-totoro",               title: "My Neighbor Totoro",                   imdb: "https://www.imdb.com/title/tt0096283/" },
  { id: "kikis-delivery-service",           title: "Kiki's Delivery Service",              imdb: "https://www.imdb.com/title/tt0097814/" },
  { id: "spirited-away",                    title: "Spirited Away",                        imdb: "https://www.imdb.com/title/tt0245429/" },
  { id: "flow",                             title: "Flow",                                 imdb: "https://www.imdb.com/title/tt4772188/" },
  { id: "oceans-11",                        title: "Ocean's 11",                           imdb: "https://www.imdb.com/title/tt0240772/" },
  { id: "back-to-the-future-3",             title: "Back to the Future 3",                 imdb: "https://www.imdb.com/title/tt0099088/" },
  { id: "ghostbusters-2016",                title: "Ghostbusters (2016)",                  imdb: "https://www.imdb.com/title/tt1289401/" },
  { id: "ghostbusters-frozen-empire",       title: "Ghostbusters: Frozen Empire",          imdb: "https://www.imdb.com/title/tt21235248/" },
  { id: "bill-and-teds-excellent-adventure", title: "Bill and Ted's Excellent Adventure",  imdb: "https://www.imdb.com/title/tt0096928/" },
  { id: "men-in-black",                     title: "Men in Black",                         imdb: "https://www.imdb.com/title/tt0119654/" },
  { id: "thor",                             title: "Thor",                                 imdb: "https://www.imdb.com/title/tt0800369/" },
  { id: "migration",                        title: "Migration",                            imdb: "https://www.imdb.com/title/tt6495056/" },
  { id: "inside-out-2",                     title: "Inside Out 2",                         imdb: "https://www.imdb.com/title/tt22022452/" },
  { id: "the-avengers",                     title: "The Avengers",                         imdb: "https://www.imdb.com/title/tt0848228/" },
  { id: "guardians-of-the-galaxy",          title: "Guardians of the Galaxy",              imdb: "https://www.imdb.com/title/tt2015381/" },
  { id: "ant-man",                          title: "Ant-Man",                              imdb: "https://www.imdb.com/title/tt0478970/" },
  { id: "thor-ragnarok",                    title: "Thor: Ragnarok",                       imdb: "https://www.imdb.com/title/tt3501632/" },
  { id: "captain-marvel",                   title: "Captain Marvel",                       imdb: "https://www.imdb.com/title/tt4154664/" },
  { id: "avengers-endgame",                 title: "Avengers: Endgame",                    imdb: "https://www.imdb.com/title/tt4154796/" },
  { id: "spider-man-no-way-home",           title: "Spider-Man: No Way Home",              imdb: "https://www.imdb.com/title/tt10872600/" },
  { id: "shang-chi",                        title: "Shang-Chi",                            imdb: "https://www.imdb.com/title/tt9376612/" },
  { id: "doctor-strange-multiverse",        title: "Doctor Strange: Multiverse of Madness", imdb: "https://www.imdb.com/title/tt9419884/" },
  { id: "barbie",                           title: "Barbie",                               imdb: "https://www.imdb.com/title/tt1517268/" },
  { id: "ant-man-quantumania",              title: "Ant-Man: Quantumania",                 imdb: "https://www.imdb.com/title/tt10954600/" },
  { id: "indiana-jones-last-crusade",       title: "Indiana Jones and the Last Crusade",   imdb: "https://www.imdb.com/title/tt0097576/" },
  { id: "ponyo",                            title: "Ponyo",                                imdb: "https://www.imdb.com/title/tt0876563/" },
  { id: "princess-mononoke",                title: "Princess Mononoke",                    imdb: "https://www.imdb.com/title/tt0119698/" },
  { id: "hunger-games-catching-fire",       title: "Hunger Games: Catching Fire",          imdb: "https://www.imdb.com/title/tt1951264/" },
  { id: "the-martian",                      title: "The Martian",                          imdb: "https://www.imdb.com/title/tt3659388/" },
  { id: "sing-2",                           title: "Sing 2",                               imdb: "https://www.imdb.com/title/tt6467266/" },
  { id: "scott-pilgrim",                    title: "Scott Pilgrim vs. the World",          imdb: "https://www.imdb.com/title/tt0446029/" },
  { id: "wakanda-forever",                  title: "Wakanda Forever",                      imdb: "https://www.imdb.com/title/tt9114286/" },
  { id: "wicked",                           title: "Wicked",                               imdb: "https://www.imdb.com/title/tt1262426/" },
  { id: "freakier-friday",                  title: "Freakier Friday",                      imdb: "https://www.imdb.com/title/tt31956415/" },
  { id: "elio",                             title: "Elio",                                 imdb: "https://www.imdb.com/title/tt4900148/" },
  { id: "spider-man-far-from-home",         title: "Spider-Man: Far From Home",            imdb: "https://www.imdb.com/title/tt6320628/" },
  { id: "monty-python-holy-grail",          title: "Monty Python and the Holy Grail",      imdb: "https://www.imdb.com/title/tt0071853/" },
  { id: "mandalorian-and-grogu",            title: "The Mandalorian and Grogu",            imdb: "https://www.imdb.com/title/tt30825738/" },
  { id: "sheep-detectives",                 title: "The Sheep Detectives",                 imdb: "https://www.imdb.com/title/tt32565993/" },
  { id: "clueless",                         title: "Clueless",                             imdb: "https://www.imdb.com/title/tt0112697/" },
  { id: "project-hail-mary",                title: "Project Hail Mary",                    imdb: "https://www.imdb.com/title/tt12042730/" },
  { id: "nimona",                           title: "Nimona",                               imdb: "https://www.imdb.com/title/tt19500164/" },
  { id: "into-the-spider-verse",            title: "Into the Spider-Verse",                imdb: "https://www.imdb.com/title/tt4633694/" },
  { id: "ratatouille",                      title: "Ratatouille",                          imdb: "https://www.imdb.com/title/tt0382932/" },
  { id: "moana",                            title: "Moana",                                imdb: "https://www.imdb.com/title/tt3521164/" },
  { id: "coco",                             title: "Coco",                                 imdb: "https://www.imdb.com/title/tt2380307/" },
  { id: "zootopia",                         title: "Zootopia",                             imdb: "https://www.imdb.com/title/tt2948356/" },
  { id: "wall-e",                           title: "WALL-E",                               imdb: "https://www.imdb.com/title/tt0910970/" },
  { id: "tangled",                          title: "Tangled",                              imdb: "https://www.imdb.com/title/tt0398286/" },
  { id: "aladdin",                          title: "Aladdin",                              imdb: "https://www.imdb.com/title/tt0103639/" },
  { id: "howls-moving-castle",              title: "Howl's Moving Castle",                 imdb: "https://www.imdb.com/title/tt0347149/" },
  { id: "wolfwalkers",                      title: "Wolfwalkers",                          imdb: "https://www.imdb.com/title/tt5198068/" },
  { id: "onward",                           title: "Onward",                               imdb: "https://www.imdb.com/title/tt7146812/" },
  { id: "turning-red",                      title: "Turning Red",                          imdb: "https://www.imdb.com/title/tt8097030/" },
  { id: "across-the-spider-verse",          title: "Across the Spider-Verse",              imdb: "https://www.imdb.com/title/tt9362722/" },
  { id: "the-little-mermaid",               title: "The Little Mermaid",                   imdb: "https://www.imdb.com/title/tt0097757/" },
  { id: "lilo-and-stitch",                  title: "Lilo & Stitch",                        imdb: "https://www.imdb.com/title/tt0275847/" },
  { id: "princess-bride",                   title: "The Princess Bride",                   imdb: "https://www.imdb.com/title/tt0093779/" },
  { id: "tmnt-mutant-mayhem",               title: "TMNT: Mutant Mayhem",                  imdb: "https://www.imdb.com/title/tt8589698/" },
  { id: "minecraft-movie",                  title: "A Minecraft Movie",                    imdb: "https://www.imdb.com/title/tt3566834/" },
  { id: "school-of-rock",                   title: "School of Rock",                       imdb: "https://www.imdb.com/title/tt0332379/" },
];
