// Full album list from Albums.md (71 albums).
const ALBUMS = [
  { id: "continuum-mayer",        title: "Continuum",                    artist: "John Mayer",               year: 2006 },
  { id: "illinois",               title: "Illinois",                     artist: "Sufjan Stevens",           year: 2005 },
  { id: "the-rip-tide",           title: "The Rip Tide",                 artist: "Beirut",                   year: 2011 },
  { id: "august",                 title: "August and Everything After",  artist: "Counting Crows",           year: 1993 },
  { id: "tidal",                  title: "Tidal",                        artist: "Fiona Apple",              year: 1996 },
  { id: "like-swimming",          title: "Like Swimming",                artist: "Morphine",                 year: 1997 },
  { id: "cure-for-pain",          title: "Cure for Pain",                artist: "Morphine",                 year: 1993 },
  { id: "the-night",              title: "The Night",                    artist: "Morphine",                 year: 2000 },
  { id: "brothers",               title: "Brothers",                     artist: "The Black Keys",           year: 2010 },
  { id: "in-return",              title: "In Return",                    artist: "ODESZA",                   year: 2014 },
  { id: "french-kiwi-juice",      title: "French Kiwi Juice",            artist: "FKJ",                      year: 2017 },
  { id: "laurel",                 title: "Laurel",                       artist: "Laurel",                   year: null },
  { id: "sleeping-operator",      title: "Sleeping Operator",            artist: "The Barr Brothers",        year: 2014 },
  { id: "every-kingdom",          title: "Every Kingdom",                artist: "Ben Howard",               year: 2011 },
  { id: "is-it",                  title: "Is It?",                       artist: "Ben Howard",               year: 2023 },
  { id: "led-zeppelin-ii",        title: "Led Zeppelin II",              artist: "Led Zeppelin",             year: 1969 },
  { id: "tapestry",               title: "Tapestry",                     artist: "Carole King",              year: 1971 },
  { id: "strange-desire",         title: "Strange Desire",               artist: "Bleachers",                year: 2014 },
  { id: "siamese-dream",          title: "Siamese Dream",                artist: "The Smashing Pumpkins",    year: 1993 },
  { id: "rumours",                title: "Rumours",                      artist: "Fleetwood Mac",            year: 1977 },
  { id: "crash",                  title: "Crash",                        artist: "Dave Matthews Band",       year: 1996 },
  { id: "sea-change",             title: "Sea Change",                   artist: "Beck",                     year: 2002 },
  { id: "legend",                 title: "Legend",                       artist: "Bob Marley & The Wailers", year: 1984 },
  { id: "the-joshua-tree",        title: "The Joshua Tree",              artist: "U2",                       year: 1987 },
  { id: "bringing-down-horse",    title: "Bringing Down the Horse",      artist: "The Wallflowers",          year: 1996 },
  { id: "baduizm",                title: "Baduizm",                      artist: "Erykah Badu",              year: 1997 },
  { id: "who-can-you-trust",      title: "Who Can You Trust?",           artist: "Morcheeba",                year: 1996 },
  { id: "white-ladder",           title: "White Ladder",                 artist: "David Gray",               year: 1998 },
  { id: "revelling-reckoning",    title: "Revelling/Reckoning",          artist: "Ani DiFranco",             year: 2001 },
  { id: "morning-after",          title: "Music for the Morning After",  artist: "Pete Yorn",                year: 2001 },
  { id: "bookends",               title: "Bookends",                     artist: "Simon & Garfunkel",        year: 1968 },
  { id: "bridge-troubled-water",  title: "Bridge Over Troubled Water",   artist: "Simon & Garfunkel",        year: 1970 },
  { id: "mezzanine",              title: "Mezzanine",                    artist: "Massive Attack",           year: 1998 },
  { id: "pnyc",                   title: "PNYC",                         artist: "Portishead",               year: 1998 },
  { id: "give-up",                title: "Give Up",                      artist: "The Postal Service",       year: 2003 },
  { id: "transatlanticism",       title: "Transatlanticism",             artist: "Death Cab for Cutie",      year: 2003 },
  { id: "philadelphonic",         title: "Philadelphonic",               artist: "G. Love & Special Sauce",  year: 1999 },
  { id: "messy",                  title: "Messy",                        artist: "Olivia Dean",              year: 2023 },
  { id: "if-it-comes-down",       title: "If It Comes Down to It",       artist: "Ruby Waters",              year: 2020 },
  { id: "whats-going-on",         title: "What's Going On",              artist: "Marvin Gaye",              year: 1971 },
  { id: "wet-leg",                title: "Wet Leg",                      artist: "Wet Leg",                  year: 2022 },
  { id: "still-in-love",          title: "I'm Still in Love with You",   artist: "Al Green",                 year: 1972 },
  { id: "no-other-love",          title: "No Other Love",                artist: "Chuck Prophet",            year: 2002 },
  { id: "the-mating-game",        title: "The Mating Game",              artist: "Bitter:Sweet",             year: 2006 },
  { id: "classics",               title: "Classics",                     artist: "Ratatat",                  year: 2006 },
  { id: "wolfgang-amadeus",       title: "Wolfgang Amadeus Phoenix",     artist: "Phoenix",                  year: 2009 },
  { id: "head-and-heart",         title: "The Head and the Heart",       artist: "The Head and the Heart",   year: 2011 },
  { id: "xx",                     title: "xx",                           artist: "The xx",                   year: 2009 },
  { id: "built-on-glass",         title: "Built on Glass",               artist: "Chet Faker",               year: 2014 },
  { id: "thinking-textures",      title: "Thinking in Textures?",        artist: "Chet Faker",               year: 2012 },
  { id: "daft-pomp",              title: "Daft Pomp",                    artist: "Pomplamoose",              year: 2022 },
  { id: "awesome-wave",           title: "An Awesome Wave",              artist: "alt-J",                    year: 2012 },
  { id: "zaba",                   title: "ZABA",                         artist: "Glass Animals",            year: 2014 },
  { id: "unplugged-clapton",      title: "Unplugged",                    artist: "Eric Clapton",             year: 1992 },
  { id: "scarlets-walk",          title: "Scarlet's Walk",               artist: "Tori Amos",                year: 2002 },
  { id: "haunted",                title: "Haunted",                      artist: "Poe",                      year: 2000 },
  { id: "hello-poe",              title: "Hello",                        artist: "Poe",                      year: 1995 },
  { id: "broken-bells",           title: "Broken Bells",                 artist: "Broken Bells",             year: 2010 },
  { id: "version-2",              title: "Version 2.0",                  artist: "Garbage",                  year: 1998 },
  { id: "first-days-spring",      title: "The First Days of Spring",     artist: "Noah and the Whale",       year: 2009 },
  { id: "trouble-will-find-me",   title: "Trouble Will Find Me",         artist: "The National",             year: 2013 },
  { id: "fumbling-ecstasy",       title: "Fumbling Towards Ecstasy",     artist: "Sarah McLachlan",          year: 1993 },
  { id: "comfort-woman",          title: "Comfort Woman",                artist: "Meshell Ndegeocello",      year: 2003 },
  { id: "brown-sugar",            title: "Brown Sugar",                  artist: "D'Angelo",                 year: 1995 },
  { id: "rock-crown",             title: "Rock Crown",                   artist: "7 Mary Three",             year: null },
  { id: "change-gonna-come",      title: "A Change Is Gonna Come",       artist: "Leela James",              year: 2005 },
  { id: "different-stars",        title: "Different Stars",              artist: "Trespassers William",      year: 2002 },
  { id: "continuum-tanerelle",    title: "Continuum",                    artist: "Tanerelle",                year: null },
  { id: "sylvan-esso",            title: "Sylvan Esso",                  artist: "Sylvan Esso",              year: 2014 },
  { id: "soon-cold-enough",       title: "Soon It Will Be Cold Enough",  artist: "Emancipator",              year: 2006 },
  { id: "daughter-of-son",        title: "Daughter of the Son",          artist: "VBND",                     year: null },
];
