// Board game list -- the "Jess" set, 84 titles.
//
// Same field contract as games-boys-night.js: id (the art-map key), title,
// players, time (minutes), bggId. Player counts and playtimes come from the
// BoardGameGeek collection export; cover art lives in art-jess.js.
window.ITEMS_JESS = [
  { id: "sherlock-holmes-consulting-detective",         title: "Sherlock Holmes Consulting Detective",          players: "1-8",  time: 90,   bggId: 296345 },
  { id: "skull",                                        title: "Skull",                                         players: "3-6",  time: 45,   bggId: 92415 },
  { id: "the-lord-of-the-rings-the-trick-taking-game",  title: "The Lord of the Rings: The Trick Taking Game",  players: "1-4",  time: 20,   bggId: 429293 },
  { id: "faraway",                                      title: "Faraway",                                       players: "2-6",  time: 30,   bggId: 385761 },
  { id: "love-letter",                                  title: "Love Letter",                                   players: "2-4",  time: 20,   bggId: 129622 },
  { id: "bomb-busters",                                 title: "Bomb Busters",                                  players: "2-5",  time: 30,   bggId: 413246 },
  { id: "point-salad",                                  title: "Point Salad",                                   players: "2-6",  time: 30,   bggId: 274960 },
  { id: "final-girl",                                   title: "Final Girl",                                    players: "1",    time: 60,   bggId: 277659 },
  { id: "captain-flip",                                 title: "Captain Flip",                                  players: "2-5",  time: 20,   bggId: 393325 },
  { id: "enchanted-plumes",                             title: "Enchanted Plumes",                              players: "2-6",  time: 40,   bggId: 322010 },
  { id: "scout",                                        title: "Scout",                                         players: "2-5",  time: 20,   bggId: 291453 },
  { id: "no-thanks",                                    title: "No Thanks!",                                    players: "3-7",  time: 20,   bggId: 12942 },
  { id: "castle-combo",                                 title: "Castle Combo",                                  players: "2-5",  time: 25,   bggId: 416851 },
  { id: "meadow",                                       title: "Meadow",                                        players: "1-4",  time: 90,   bggId: 314491 },
  { id: "dorfromantik",                                 title: "Dorfromantik",                                  players: "1-6",  time: 60,   bggId: 370591 },
  { id: "dracula-vs-van-helsing",                       title: "Dracula vs Van Helsing",                        players: "2",    time: 45,   bggId: 381278 },
  { id: "sea-salt-paper",                               title: "Sea Salt & Paper",                              players: "2-4",  time: 45,   bggId: 367220 },
  { id: "root",                                         title: "Root",                                          players: "2-4",  time: 90,   bggId: 237182 },
  { id: "a-gentle-rain",                                title: "A Gentle Rain",                                 players: "1",    time: 15,   bggId: 334011 },
  { id: "inheritors",                                   title: "Inheritors",                                    players: "2-4",  time: 45,   bggId: 367476 },
  { id: "splendor-duel",                                title: "Splendor Duel",                                 players: "2",    time: 30,   bggId: 364073 },
  { id: "for-sale",                                     title: "For Sale",                                      players: "3-6",  time: 30,   bggId: 172 },
  { id: "canopy",                                       title: "Canopy",                                        players: "1-4",  time: 30,   bggId: 295607 },
  { id: "wyrmspan",                                     title: "Wyrmspan",                                      players: "1-5",  time: 90,   bggId: 410201 },
  { id: "courtisans",                                   title: "Courtisans",                                    players: "2-5",  time: 30,   bggId: 402283 },
  { id: "pinched",                                      title: "Pinched!",                                      players: "2-5",  time: 60,   bggId: 450685 },
  { id: "caesar",                                       title: "Caesar!",                                       players: "1-2",  time: 20,   bggId: 338957 },
  { id: "7-wonders-duel",                               title: "7 Wonders Duel",                                players: "2",    time: 30,   bggId: 173346 },
  { id: "jaipur",                                       title: "Jaipur",                                        players: "2",    time: 30,   bggId: 54043 },
  { id: "land-vs-sea",                                  title: "Land vs Sea",                                   players: "2-4",  time: 40,   bggId: 336929 },
  { id: "terror-in-meeple-city",                        title: "Terror in Meeple City",                         players: "2-4",  time: 30,   bggId: 97903 },
  { id: "calico",                                       title: "Calico",                                        players: "1-4",  time: 45,   bggId: 283155 },
  { id: "fugitive",                                     title: "Fugitive",                                      players: "2",    time: 20,   bggId: 197443 },
  { id: "animal-kingdoms",                              title: "Animal Kingdoms",                               players: "1-5",  time: 45,   bggId: 256513 },
  { id: "tiny-towns",                                   title: "Tiny Towns",                                    players: "1-6",  time: 60,   bggId: 265736 },
  { id: "boop",                                         title: "boop",                                          players: "2",    time: 30,   bggId: 355433 },
  { id: "witchcraft",                                   title: "Witchcraft!",                                   players: "1",    time: 40,   bggId: 383499 },
  { id: "the-lord-of-the-rings-duel-for-middle-earth",  title: "The Lord of the Rings: Duel for Middle-earth",  players: "2",    time: 30,   bggId: 421006 },
  { id: "mycelia",                                      title: "Mycelia",                                       players: "1-4",  time: 45,   bggId: 392023 },
  { id: "libertalia-winds-of-galecrest",                title: "Libertalia: Winds of Galecrest",                players: "1-6",  time: 60,   bggId: 356033 },
  { id: "the-vale-of-eternity",                         title: "The Vale of Eternity",                          players: "2-4",  time: 45,   bggId: 385529 },
  { id: "sleeping-gods-primeval-peril",                 title: "Sleeping Gods: Primeval Peril",                 players: "1-2",  time: 240,  bggId: 362205 },
  { id: "in-the-footsteps-of-darwin",                   title: "In the Footsteps of Darwin",                    players: "2-5",  time: 30,   bggId: 376683 },
  { id: "district-noir",                                title: "District Noir",                                 players: "2",    time: 20,   bggId: 216497 },
  { id: "middle-ages",                                  title: "Middle Ages",                                   players: "2-5",  time: 30,   bggId: 403754 },
  { id: "critter-kitchen",                              title: "Critter Kitchen",                               players: "1-5",  time: 60,   bggId: 393429 },
  { id: "paranormal-detectives",                        title: "Paranormal Detectives",                         players: "2-6",  time: 50,   bggId: 280136 },
  { id: "silver-gold",                                  title: "Silver & Gold",                                 players: "2-4",  time: 20,   bggId: 270673 },
  { id: "castles-by-the-sea",                           title: "Castles by the Sea",                            players: "1-4",  time: 60,   bggId: 357841 },
  { id: "the-wolves",                                   title: "The Wolves",                                    players: "2-5",  time: 75,   bggId: 368058 },
  { id: "fountains",                                    title: "Fountains",                                     players: "1-5",  time: 45,   bggId: 440509 },
  { id: "pagan-fate-of-roanoke",                        title: "Pagan: Fate of Roanoke",                        players: "2",    time: 60,   bggId: 319910 },
  { id: "cubirds",                                      title: "CuBirds",                                       players: "2-5",  time: 20,   bggId: 245476 },
  { id: "ichor",                                        title: "Ichor",                                         players: "2",    time: 40,   bggId: 420915 },
  { id: "spots",                                        title: "Spots",                                         players: "1-4",  time: 30,   bggId: 372559 },
  { id: "kronologic-paris-1920",                        title: "Kronologic: Paris 1920",                        players: "1-4",  time: 30,   bggId: 402111 },
  { id: "harvest",                                      title: "Harvest",                                       players: "1-4",  time: 60,   bggId: 395623 },
  { id: "wandering-towers",                             title: "Wandering Towers",                              players: "1-6",  time: 30,   bggId: 355483 },
  { id: "truffle-shuffle",                              title: "Truffle Shuffle",                               players: "2-4",  time: 30,   bggId: 298060 },
  { id: "the-hobbit-there-and-back-again",              title: "The Hobbit: There and Back Again",              players: "1-4",  time: 30,   bggId: 436215 },
  { id: "parks",                                        title: "PARKS",                                         players: "1-5",  time: 60,   bggId: 266524 },
  { id: "flamecraft",                                   title: "Flamecraft",                                    players: "1-5",  time: 60,   bggId: 336986 },
  { id: "lost-cities",                                  title: "Lost Cities",                                   players: "2",    time: 30,   bggId: 50 },
  { id: "paris-la-cite-de-la-lumiere",                  title: "Paris: La Cité de la Lumière",                  players: "2",    time: 30,   bggId: 276498 },
  { id: "guillotine",                                   title: "Guillotine",                                    players: "2-5",  time: 30,   bggId: 116 },
  { id: "photosynthesis",                               title: "Photosynthesis",                                players: "2-4",  time: 60,   bggId: 218603 },
  { id: "deep-regrets",                                 title: "Deep Regrets",                                  players: "1-5",  time: 150,  bggId: 397931 },
  { id: "brew",                                         title: "Brew",                                          players: "2-4",  time: 90,   bggId: 332386 },
  { id: "rebirth",                                      title: "Rebirth",                                       players: "2-4",  time: 60,   bggId: 417197 },
  { id: "fishing",                                      title: "Fishing",                                       players: "3-5",  time: 60,   bggId: 419195 },
  { id: "clank-catacombs",                              title: "Clank!: Catacombs",                             players: "2-4",  time: 90,   bggId: 365717 },
  { id: "gudnak",                                       title: "Gudnak",                                        players: "2-4",  time: 25,   bggId: 354923 },
  { id: "oceans",                                       title: "Oceans",                                        players: "2-4",  time: 90,   bggId: 232414 },
  { id: "hercules-and-the-12-labors",                   title: "Hercules and the 12 Labors",                    players: "1",    time: 60,   bggId: 436038 },
  { id: "cat-lady",                                     title: "Cat Lady",                                      players: "2-4",  time: 30,   bggId: 228504 },
  { id: "ra",                                           title: "Ra",                                            players: "2-5",  time: 60,   bggId: 12 },
  { id: "forest-shuffle",                               title: "Forest Shuffle",                                players: "2-5",  time: 60,   bggId: 391163 },
  { id: "wild-gardens",                                 title: "Wild Gardens",                                  players: "1-4",  time: 120,  bggId: 371133 },
  { id: "point-galaxy",                                 title: "Point Galaxy",                                  players: "1-5",  time: 30,   bggId: 431998 },
  { id: "the-quest-for-el-dorado",                      title: "The Quest for El Dorado",                       players: "2-4",  time: 60,   bggId: 217372 },
  { id: "ego",                                          title: "EGO",                                           players: "2-5",  time: 80,   bggId: 429766 },
  { id: "royal-visit",                                  title: "Royal Visit",                                   players: "2",    time: 30,   bggId: 22245 },
  { id: "knarr",                                        title: "Knarr",                                         players: "2-4",  time: 30,   bggId: 379629 },
  { id: "great-western-trail",                          title: "Great Western Trail",                           players: "2-4",  time: 150,  bggId: 193738 },
];
